version: "3"
services:
  db:
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voting
    volumes:
      - pgsql-data:/var/lib/postgresql/data
  voting-service:
    build: .
    command: bash -c "npm i && ./start.sh"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_DATABASE: voting
      DB_SCHEMA: public
      DB_SSL: 0
      SSL_REDIRECTION_ENABLED: 0
    volumes:
      - .:/opt/app
    ports:
      - ${VOTING_SERVICE_PORT:-3000}:3000
      - 9229:9229
    depends_on:
      - db
volumes:
  pgsql-data:
  redis-data:
