name: Build and test

on:
  pull_request:
  push:
    branches:
      - development
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: production

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: voting
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm install
        env:
          NODE_ENV: development

      - name: Static Code Analysis
        run: npm run lint

      - name: Run Tests
        run: npm run test:cov

      - name: Build
        run: npm run build
